-- ============================================================
-- FileUploadServer 完整数据库表结构 (PostgreSQL)
-- ============================================================
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "ApiKeys" (
    "Id"            integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key"           text                        NOT NULL,
    "Description"   text                        NOT NULL DEFAULT '',
    "CreatedAt"     timestamp with time zone    NOT NULL,
    "ExpiresAt"     timestamp with time zone    NOT NULL,
    "IsDeleted"     boolean                     NOT NULL DEFAULT FALSE,
    "KeyType"       text                        NOT NULL DEFAULT 'Admin',
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "IpWhitelists" (
    "Id"            integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress"     text                        NOT NULL,
    "Description"   text                        NOT NULL DEFAULT '',
    "CreatedAt"     timestamp with time zone    NOT NULL,
    "IsEnabled"     boolean                     NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_IpWhitelists" PRIMARY KEY ("Id")
);

CREATE TABLE "Files" (
    "Id"                integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FileName"          text                        NOT NULL,
    "StoredFileName"    text                        NOT NULL,
    "FileSize"          bigint                      NOT NULL,
    "ContentType"       text                        NOT NULL,
    "UploadedAt"        timestamp with time zone    NOT NULL DEFAULT NOW(),
    "ApiKeyId"          integer                     NULL,
    "EncryptionVersion" smallint                    NOT NULL DEFAULT 0,
    "KeyVersion"        smallint                    NOT NULL DEFAULT 0,
    "DiskFileName"      text                        NOT NULL DEFAULT '',
    "FileHash"          text                        NULL,
    "BlockSize"         integer                     NOT NULL DEFAULT 1048576,
    "IsPublic"          boolean                     NOT NULL DEFAULT FALSE,
    "PublicPath"        text                        NULL,
    "StorageMode"       text                        NOT NULL DEFAULT 'Local',
    "ClientId"          text                        NULL,
    "StoragePath"       text                        NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_ApiKeys_ApiKeyId"
        FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Files_ApiKeyId"       ON "Files" ("ApiKeyId");
CREATE INDEX "IX_Files_DiskFileName"   ON "Files" ("DiskFileName");
CREATE INDEX "IX_Files_IsPublic"       ON "Files" ("IsPublic");

CREATE TABLE "WsClients" (
    "Id"                text                        NOT NULL,
    "ClientSecretHash"  text                        NOT NULL,
    "Description"       text                        NOT NULL DEFAULT '',
    "IsEnabled"         boolean                     NOT NULL DEFAULT TRUE,
    "PathPrefixes"      text                        NOT NULL DEFAULT '',
    "StorageCapacity"   bigint                      NOT NULL DEFAULT -1,
    "CurrentStorage"    bigint                      NOT NULL DEFAULT 0,
    "LastConnectedAt"   timestamp with time zone    NULL,
    "CreatedAt"         timestamp with time zone    NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_WsClients" PRIMARY KEY ("Id")
);

CREATE TABLE "FileLocations" (
    "Id"            uuid                        NOT NULL,
    "FilePath"      text                        NOT NULL,
    "FileName"      text                        NOT NULL,
    "FileSize"      bigint                      NOT NULL,
    "FileHash"      text                        NULL,
    "ClientId"      text                        NOT NULL,
    "ApiKeyId"      integer                     NOT NULL,
    "IsPublic"      boolean                     NOT NULL DEFAULT FALSE,
    "CreatedAt"     timestamp with time zone    NOT NULL DEFAULT NOW(),
    "ExpiresAt"     timestamp with time zone    NULL,
    CONSTRAINT "PK_FileLocations" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_FileLocations_FilePath"   ON "FileLocations" ("FilePath");
CREATE INDEX "IX_FileLocations_ClientId"   ON "FileLocations" ("ClientId");
CREATE INDEX "IX_FileLocations_IsPublic"   ON "FileLocations" ("IsPublic");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20250330000000_InitialCreate',                '10.0.5'),
    ('20260710000000_AddEncryptionAndWsSupport',    '10.0.5');
