-- ============================================================
-- FileUploadServer 完整数据库表结构 (PostgreSQL)
-- 生成时间：2026-07-10
-- 基于 EF Core Migration + AppDbContextModelSnapshot
-- ============================================================

-- ============================================================
-- 1. __EFMigrationsHistory 表（迁移历史记录）
-- ============================================================
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ============================================================
-- 2. ApiKeys — API 密钥表
-- ============================================================
CREATE TABLE "ApiKeys" (
    "Id"            integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key"           text                        NOT NULL,
    "Description"   text                        NOT NULL DEFAULT '',
    "CreatedAt"     timestamp with time zone    NOT NULL,
    "ExpiresAt"     timestamp with time zone    NOT NULL,
    "IsDeleted"     boolean                     NOT NULL DEFAULT FALSE,
    "KeyType"       text                        NOT NULL DEFAULT 'Admin',
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id")
);

COMMENT ON TABLE "ApiKeys" IS 'API密钥表：Admin 和 Temporary 两种类型';
COMMENT ON COLUMN "ApiKeys"."KeyType" IS 'Admin=管理密钥, Temporary=临时密钥';

-- ============================================================
-- 3. IpWhitelists — IP 白名单表
-- ============================================================
CREATE TABLE "IpWhitelists" (
    "Id"            integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IpAddress"     text                        NOT NULL,
    "Description"   text                        NOT NULL DEFAULT '',
    "CreatedAt"     timestamp with time zone    NOT NULL,
    "IsEnabled"     boolean                     NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_IpWhitelists" PRIMARY KEY ("Id")
);

COMMENT ON TABLE "IpWhitelists" IS 'IP白名单：用于限制公网临时密钥申请';

-- ============================================================
-- 4. Files — 文件记录表
-- ============================================================
CREATE TABLE "Files" (
    -- 基础字段（InitialCreate）
    "Id"                integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FileName"          text                        NOT NULL,
    "StoredFileName"    text                        NOT NULL,
    "FileSize"          bigint                      NOT NULL,
    "ContentType"       text                        NOT NULL,
    "UploadedAt"        timestamp with time zone    NOT NULL DEFAULT NOW(),

    -- 外键关联
    "ApiKeyId"          integer                     NULL,

    -- 加密字段（Phase 1.5）
    "EncryptionVersion" smallint                    NOT NULL DEFAULT 0,
    "KeyVersion"        smallint                    NOT NULL DEFAULT 0,
    "DiskFileName"      text                        NOT NULL DEFAULT '',
    "FileHash"          text                        NULL,
    "BlockSize"         integer                     NOT NULL DEFAULT 1048576,

    -- 公共访问字段（Phase 2）
    "IsPublic"          boolean                     NOT NULL DEFAULT FALSE,
    "PublicPath"        text                        NULL,

    -- WS 存储字段（Phase 3）
    "StorageMode"       text                        NOT NULL DEFAULT 'Local',
    "ClientId"          text                        NULL,
    "StoragePath"       text                        NULL,

    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_ApiKeys_ApiKeyId"
        FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id")
        ON DELETE SET NULL
);

-- Files 索引
CREATE INDEX "IX_Files_ApiKeyId"       ON "Files" ("ApiKeyId");
CREATE INDEX "IX_Files_DiskFileName"   ON "Files" ("DiskFileName");
CREATE INDEX "IX_Files_IsPublic"       ON "Files" ("IsPublic");

COMMENT ON TABLE "Files" IS '文件记录表：支持加密、公共访问、WS分布式存储';
COMMENT ON COLUMN "Files"."EncryptionVersion" IS '0=未加密, 1=AES-256-GCM分块';
COMMENT ON COLUMN "Files"."KeyVersion"        IS '加密密钥版本号';
COMMENT ON COLUMN "Files"."DiskFileName"      IS '磁盘上的加密/随机文件名（含子目录前缀）';
COMMENT ON COLUMN "Files"."StorageMode"       IS 'Local=本地, WebSocket=远程, Hybrid=混合';

-- ============================================================
-- 5. WsClients — WS 客户端注册表
-- ============================================================
CREATE TABLE "WsClients" (
    "Id"                text                        NOT NULL,
    "ClientSecretHash"  text                        NOT NULL,
    "Description"       text                        NOT NULL DEFAULT '',
    "IsEnabled"         boolean                     NOT NULL DEFAULT TRUE,
    "PathPrefixes"      text                        NOT NULL DEFAULT '',
    "StorageCapacity"   bigint                      NOT NULL DEFAULT -1,
    "CurrentStorage"    bigint                      NOT NULL DEFAULT 0,
    "LastConnectedAt"   timestamp with time zone    NULL,
    "CreatedAt"         timestamp with time zone    NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_WsClients" PRIMARY KEY ("Id")
);

COMMENT ON TABLE "WsClients" IS 'WebSocket客户端注册表：存储节点管理';
COMMENT ON COLUMN "WsClients"."Id"               IS '客户端唯一标识';
COMMENT ON COLUMN "WsClients"."ClientSecretHash" IS 'SHA256(clientSecret)';
COMMENT ON COLUMN "WsClients"."PathPrefixes"     IS '逗号分隔的路径前缀，如 /public/*,/shared/*';
COMMENT ON COLUMN "WsClients"."StorageCapacity"  IS '-1=无限制';

-- ============================================================
-- 6. FileLocations — 文件位置表（WS 客户端存储）
-- ============================================================
CREATE TABLE "FileLocations" (
    "Id"            uuid                        NOT NULL,
    "FilePath"      text                        NOT NULL,
    "FileName"      text                        NOT NULL,
    "FileSize"      bigint                      NOT NULL,
    "FileHash"      text                        NULL,
    "ClientId"      text                        NOT NULL,
    "ApiKeyId"      integer                     NOT NULL,
    "IsPublic"      boolean                     NOT NULL DEFAULT FALSE,
    "CreatedAt"     timestamp with time zone    NOT NULL DEFAULT NOW(),
    "ExpiresAt"     timestamp with time zone    NULL,
    CONSTRAINT "PK_FileLocations" PRIMARY KEY ("Id")
);

-- FileLocations 索引
CREATE INDEX "IX_FileLocations_FilePath"   ON "FileLocations" ("FilePath");
CREATE INDEX "IX_FileLocations_ClientId"   ON "FileLocations" ("ClientId");
CREATE INDEX "IX_FileLocations_IsPublic"   ON "FileLocations" ("IsPublic");

COMMENT ON TABLE "FileLocations" IS '文件位置记录表：记录文件存储在哪个WS客户端节点';

-- ============================================================
-- 7. StorageConfigs — 存储路由配置表（Phase 4）
--    注意：此表在 ModelSnapshot 中尚未启用，但在 PLAN 中已定义。
--    如需使用 Hybrid 模式路径路由，取消注释执行。
-- ============================================================
-- CREATE TABLE "StorageConfigs" (
--     "Id"            integer                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     "PathPattern"   text                        NOT NULL,
--     "StorageMode"   text                        NOT NULL DEFAULT 'Local',
--     "ClientId"      text                        NULL,
--     "Priority"      integer                     NOT NULL DEFAULT 0,
--     "CreatedAt"     timestamp with time zone    NOT NULL DEFAULT NOW(),
--     CONSTRAINT "PK_StorageConfigs" PRIMARY KEY ("Id")
-- );
-- CREATE INDEX "IX_StorageConfigs_PathPattern" ON "StorageConfigs" ("PathPattern");
-- CREATE INDEX "IX_StorageConfigs_Priority"    ON "StorageConfigs" ("Priority");

-- ============================================================
-- 初始化迁移历史记录
-- ============================================================
-- 注意：执行此脚本后，数据库已处于最新状态，不再需要运行 dotnet ef database update
-- 如果需要后续使用 EF Core Migration，请插入以下记录：
--
-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
-- VALUES
--     ('20250330000000_InitialCreate',                '10.0.5'),
--     ('20260710000000_AddEncryptionAndWsSupport',    '10.0.5');
